#配置文件
server:
  port: 8889
spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  #json序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  #redis配置
  redis:
    host: 47.xxx.xx.xxx
    port: 6381
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
    password: xihuanni
    database: 2

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: com.wzxlq.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
